apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  labels:
    app: my-web
spec:
  selector:
    app: my-web
  ports:
  - protocol: TCP
    port: 80      # The port that the service exposes
    targetPort: 80 # The port on the container to route traffic to
  type: ClusterIP # Change to NodePort or LoadBalancer if external access is required
